name: smiles2docking
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit
  - openbabel
  - pandas
  - pyyaml
  - openpyxl
  - matplotlib
  - pyside6
  - pyinstaller
  - pytest
  - joblib
  - pip
  - pip:
      - typing-extensions
      - dimorphite-dl>=1.3
      - meeko>=0.5
